export const station_list = {
  n211_toward: [
    'Neuperlach Süd (S)(U), München',
    'W.-Heisenberg-W., Neubiberg',
    'Neubiberg (S), Neubiberg',
    'Rathaus, Neubiberg',
    'Kaiserstraße, Neubiberg',
    'Barbarossastraße, Neubiberg',
    'Schulzstraße, Neubiberg',
    'Wotanstraße, Neubiberg',
    'Lena-Christ-Straße, Neubiberg',
    'Anzengruberstr., Neubiberg',
    'Neubiberger Straße, Putzbrunn',
    'Isarweg, Putzbrunn',
  ],
  n211_backward: [
    'Isarweg, Putzbrunn',
    'Neubiberger Straße, Putzbrunn',
    'Anzengruberstr., Neubiberg',
    'Lena-Christ-Straße, Neubiberg',
    'Wotanstraße, Neubiberg',
    'Schulzstraße, Neubiberg',
    'Barbarossastraße, Neubiberg',
    'Kaiserstraße, Neubiberg',
    'Neubiberg (S), Neubiberg',
    'W.-Heisenberg-W., Neubiberg',
    'Neuperlach Süd (S)(U), München',
  ],
  n212_toward: [
    'Neuperlach Süd (S)(U), München',
    'W.-Heisenberg-W., Neubiberg',
    'Neubiberg (S), Neubiberg',
    'Rathaus, Neubiberg',
    'Kaiserstraße, Neubiberg',
    'Barbarossastraße, Neubiberg',
    'Schulzstraße, Neubiberg',
    'Wotanstraße, Neubiberg',
    'Lena-Christ-Straße, Neubiberg',
    'Anzengruberstr., Neubiberg',
    'Neubiberger Straße, Putzbrunn',
    'Isarweg, Putzbrunn',
    'Ödenstockach, Ort, Oedenstockach',
    'Andr.-Wagner-Str., Solalinden',
    'Am Hochstand, Solalinden',
    'Putzbrunn, Kirchenzentrum, Putzbrunn',
    'Hohenbrunner Straße, Putzbrunn',
  ],
  n212_backward: [
    'Hohenbrunner Straße, Putzbrunn',
    'Putzbrunn, Kirchenzentrum, Putzbrunn',
    'Am Hochstand, Solalinden',
    'Andr.-Wagner-Str., Solalinden',
    'Ödenstockach, Ort, Oedenstockach',
    'Isarweg, Putzbrunn',
    'Neubiberger Straße, Putzbrunn',
    'Anzengruberstr., Neubiberg',
    'Lena-Christ-Straße, Neubiberg',
    'Wotanstraße, Neubiberg',
    'Schulzstraße, Neubiberg',
    'Barbarossastraße, Neubiberg',
    'Kaiserstraße, Neubiberg',
    'Neubiberg (S), Neubiberg',
    'W.-Heisenberg-W., Neubiberg',
    'Neuperlach Süd (S)(U), München',
  ],
};
